import arcade.key as k

# Game proprieties
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 850
SCREEN_TITLE = "Funny Game"

SPRINT_VALUE = 2
CROUCH_VALUE = 0.5

TILE_SIZE = 100

MAP_SIZE_X = TILE_SIZE * 20
MAP_SIZE_Y = TILE_SIZE * 20

TILE_OFFSET = 1

# Key bindings
UP_BINDING = k.W
DOWN_BINDING = k.S
LEFT_BINDING = k.A
RIGHT_BINDING = k.D

SPRINT_BINDING = k.LSHIFT
SPRINT_MOD_BINDING = k.MOD_SHIFT

CROUCH_BINDING = k.LCTRL
CROUCH_MOD_BINDING = k.MOD_CTRL
